apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
spec:
  name: prometheus-grafanadatasource.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc:9091'
      access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      secureJsonData:
        httpHeaderValue1: 'Bearer CHANGEME'
