apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kcp-glbc-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kcp-glbc-controller-manager
subjects:
  - kind: ServiceAccount
    name: default
