apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kcp-glbc-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
