rule_files:
  - ../rules-glbc.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: glbc_aws_route53_request_duration_seconds_bucket{pod="glbc"}
        values: "0+0x60 2+2x65"
      - series: glbc_aws_route53_request_duration_seconds_count{pod="glbc"}
        values: "2+4x125"
    alert_rule_test:
      - eval_time: 60m
        alertname: HighDNSLatencyAlert
        exp_alerts: []
      - eval_time: 125m
        alertname: HighDNSLatencyAlert
        exp_alerts:
          - exp_labels:
              severity: warning
            exp_annotations:
              summary: 'Summary of the alert'
              description: 'More detailed description of the alert and cause of firing'
              runbook_url: 'https://github.com/Kuadrant/kcp-glbc/blob/main/docs/observability/runbooks/HighDNSLatencyAlert.adoc'