apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: glbc
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - "*"
