apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncer
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - serviceaccounts
  - services
  - secrets
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - "*"  

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syncer
subjects:
- kind: ServiceAccount
  name: kcp
  namespace: kcp-pcluster

