
resources:
  - service_account.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - ocp-injected-certs.yaml
  - grafana_route.yaml
  - grafana.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: grafana-proxy
    literals:
      - session_secret=CHANGEME
